apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: alb-controller-test
  region: ap-northeast-2
  version: "1.27"

vpc:
  cidr: "10.0.0.0/16"

managedNodeGroups:
- name: spot
  spot: true
  instanceTypes: ["t3.large"]
  minSize: 2
  maxSize: 2
  desiredCapacity: 2
  volumeSize: 10
  privateNetworking: true
